name: Zip Files

on: 
  push:
  create:
     tags:
      - v*


jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: papeloto/action-zip@v1
        with:
          files: assets/ pack.mcmeta pack.png
          recursive: true
          dest: result.zip
      - uses: actions/upload-artifact@v1
        with:
          name: result.zip
          path: ${{ github.workspace }}/result.zip

