name: Zip Files

on:
  release:
    types: [push]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: assets/ pack.mcmeta/ pack.png
          recursive: true
          dest: result.zip
